// ForkIt — Content strings, copy arrays, and tour step definitions

export const FORKING_LINES = [
  'Picking for you…',
  'One sec…',
  'Finding food…',
  'Consulting the vibes…',
  'Rolling the dinner dice…',
  'Cross-referencing cravings…',
  'Selecting your destiny…',
  'Spearing the perfect spot…',
  'Pronging through possibilities…',
  'Overthinking is over…',
  'Almost there…',
];

export const SUCCESS_LINES = [
  'There. Done. Go eat.',
  'Picked. Now go.',
  "That's the one.",
  'Decision made.',
  'Done. Stop scrolling. Go.',
  'No more debates. Just go.',
];

export const FAIL_LINES = [
  'Nothing? Lower your standards.',
  'Zero results. Widen the radius.',
  'Your filters said no to everything.',
  'Too picky. Loosen up.',
];

// Last reviewed: 2026-03-22. To update: add lowercase chain name keywords.
// Detection also requires 500+ reviews (see looksLikeChain in utils/helpers.js).
export const CHAIN_KEYWORDS = [
  'applebee',
  'arbys',
  'auntie anne',
  'auntie annes',
  'baja fresh',
  'baskin-robbins',
  'baskin robbins',
  'benihana',
  "bj's restaurant",
  'bjs restaurant',
  'blaze pizza',
  'bob evans',
  'bojangles',
  'bonchon',
  'bonefish grill',
  'buca di beppo',
  'buc-ee',
  'bucees',
  'buffalo wild wings',
  'burger king',
  'cafe rio',
  'capital grille',
  'carrabba',
  "carl's jr",
  'cava',
  'checkers',
  'cheesecake factory',
  'chick-fil-a',
  'chickfila',
  'chili',
  'chipotle',
  'chopt',
  "church's chicken",
  'churchs chicken',
  'cicis',
  'cinnabon',
  'cold stone',
  'cook-out',
  'cracker barrel',
  'culver',
  'dairy queen',
  'del taco',
  'denny',
  'domino',
  'dunkin',
  'dutch bros',
  'el pollo loco',
  'fazoli',
  'firehouse subs',
  'first watch',
  'five guys',
  'fogo de chao',
  'fogo de chão',
  'freddy',
  'golden corral',
  'hardee',
  'hunt brothers pizza',
  'ihop',
  'in-n-out',
  'jack in the box',
  'jamba',
  "jason's deli",
  'jasons deli',
  'jersey mike',
  'jimmy john',
  "joe's crab shack",
  'joes crab shack',
  'kfc',
  'krispy kreme',
  'little caesars',
  "logan's roadhouse",
  'logans roadhouse',
  'long john silver',
  'longhorn steakhouse',
  'macaroni grill',
  'marble slab',
  "marco's pizza",
  'marcos pizza',
  'mcalister',
  'mcdonald',
  "moe's southwest",
  'moes southwest',
  'mod pizza',
  "morton's the steakhouse",
  'mortons the steakhouse',
  'olive garden',
  'on the border',
  'orange julius',
  'outback',
  'panda express',
  'panera',
  'papa john',
  'papa murphy',
  "peet's coffee",
  'peets coffee',
  'perkins restaurant',
  'pf chang',
  'p.f. chang',
  'pei wei',
  'pizza hut',
  'planet smoothie',
  'popeyes',
  'portillo',
  'potbelly',
  'qdoba',
  'quiznos',
  'raising cane',
  'red lobster',
  'red robin',
  'round table',
  'rubio',
  'ruby tuesday',
  "ruth's chris",
  'ruths chris',
  'sbarro',
  'schlotzsky',
  "scooter's coffee",
  'scooters coffee',
  'shake shack',
  'sheetz',
  'shoney',
  'sizzler',
  'slim chickens',
  'smashburger',
  'smoothie king',
  'sonic',
  'starbucks',
  'steak n shake',
  "steak 'n shake",
  'subway',
  'sweetgreen',
  'taco bell',
  'texas roadhouse',
  'tgi friday',
  'tim hortons',
  'tropical smoothie',
  'village inn',
  'waffle house',
  'wawa',
  'wendy',
  'whataburger',
  'which wich',
  'white castle',
  'wingstop',
  'yard house',
  'zaxby',
];

export const SIGNATURE_DISH_RULES = [
  { match: ['mcdonald'], dish: 'Big Mac' },
  { match: ['chick-fil-a', 'chickfila'], dish: 'Chick-fil-A Chicken Sandwich' },
  { match: ['taco bell'], dish: 'Crunchwrap Supreme' },
  { match: ['chipotle'], dish: 'Chicken Burrito Bowl' },
  { match: ['wendy'], dish: 'Baconator' },
  { match: ['popeyes'], dish: 'Spicy Chicken Sandwich' },
  { match: ['kfc'], dish: 'Original Recipe Fried Chicken' },
  { match: ['starbucks'], dish: 'Caramel Macchiato' },
];

// Tour steps — ref values are string keys matching tourRefs object properties.
// Look up the actual ref at usage time via tourRefs[step.ref].
export const TOUR_STEPS = [
  {
    ref: 'forkBtn',
    title: 'Just fork it.',
    desc: "Tap the button and we'll pick a spot. Each tap re-rolls from the same pool for free. A new search only counts when your filters change or the pool refreshes.",
  },
  {
    ref: 'filtersToggle',
    title: 'Your Filters',
    desc: 'Distance, walk/drive mode, cuisine keywords, exclude keywords, and hidden gems \u2014 all free, always yours. Tap the pin to search near a custom address. Try "tacos" and exclude "Taco Bell."',
    expandFilters: true,
  },
  {
    ref: 'maxDamageRow',
    title: 'Pro Filters',
    desc: 'Price ceiling, minimum star rating, and open-now filter are Pro features. Plus, Pro picks show the full card with two alternative picks in different categories.',
    mockContent: 'proFilters',
  },
  {
    ref: 'listsRow',
    title: 'Make It Yours',
    desc: 'The more you fork, the better it gets. Save the ones you love, block the ones you don\u2019t, add your own spots, and check your history anytime. Back up or restore from Info.',
    mockContent: 'yourLists',
  },
  {
    ref: 'forkAroundBtn',
    title: 'Fork Around. Find Out.',
    desc: 'No more "where should we eat?" Share a code, everyone sets their own filters privately, and we pick one place that works for everyone. Host 1 free/month, join unlimited.',
    mockContent: 'forkAround',
  },
  {
    ref: null,
    mock: true,
    title: 'Ready to upgrade?',
    desc: (price) =>
      `Pro (${price}/month) unlocks all filters, full details, alternative picks, and 3 group sessions. Pro+ adds unlimited everything.`,
    mockContent: 'upgrade',
  },
];
